#!/bin/sh

tmux start-server
tmux new-session -d -s 'cellepathy'
tmux rename-window 'code'
tmux new-window -n 'git' -c '/home/prajmus/Cellepathy/gerrit/KnoGo'
tmux new-window -n 'gradle' -c '/home/prajmus/Cellepathy/gerrit/KnoGo-Client-Java'
tmux new-window -n 'vim' -c '/home/prajmus/Cellepathy/'
tmux new-window -n 'django' -c '/home/prajmus/Cellepathy/gerrit/KnoGo'

tmux send-keys -t 'code' 'cell; clear' C-m

tmux select-window -t 'code'

tmux -2 attach-session -d -t 'cellepathy'
